<?php
    echo "<form>";
    echo "<h1>Data Tahun 2022</h1>";
    echo "<table width='0'>";
    echo "<tr>";
    echo "<td>";
    echo "Nama";
    echo "</td>";
    echo "<td>";
    echo ":";
    echo "</td>";
    echo "<td>";
    echo "<input type='text' id='nama' name='nama'>";
    echo "</td>";
    echo "</tr>";
    echo "<tr>";
    echo "<td>";
    echo "Alamat";
    echo "</td>";
    echo "<td>";
    echo ":";
    echo "</td>";
    echo "<td>";
    echo "<input type='text' id='alamat' name='alamat'>";
    echo "</td>";
    echo "</tr>";
    echo "<tr>";
    echo "<td>";
    echo "Umur";
    echo "</td>";
    echo "<td>";
    echo ":";
    echo "</td>";
    echo "<td>";
    echo "<input type='text' id='umur' name='umur'>";
    echo "</td>";
    echo "</tr>";
    echo "<tr>";
    echo "<td>";
    echo "Pekerjaan";
    echo "</td>";
    echo "<td>";
    echo ":";
    echo "</td>";
    echo "<td>";
    echo "<input type='text' id='pekerjaan' name='pekerjaan'>";
    echo "</td>";
    echo "</tr>";
    echo "</table>";
    echo "</form>";
?>